### ISSUE TITLE
OpenCV

### ISSUE THREAD

**Issue by Cyper77** [Hermann-SW/fork-raspiraw#2]
can we use this capture method with openCV ?
if you dont bother, how?
also: can we use on tinkerboard ?
thnx.

**Comment by Hermann-SW** [comment]
Hi,
you can use raspiraw with OpenCV, but only with small framerate since OpenCV processing for edge detection does not allow to process more than 50 frames per second :-(
Here are the instructions on how, and the next posting is about the 20ms rstriction even for really small frame:
https://www.raspberrypi.org/forums/viewtopic.php?t=189661#p1250336

Raspiraw is for Raspberries.
If you want to run it on tinkerboard, you need to port it.
Should be possible.

**Comment by bhjelstrom** [comment]
Hermann,

Thanks for all of your work on this. I have a few questions.
1. When using raspiraw, debayering happens on the CPU rather than camera ISP or RPI GPU, correct?
2. I noticed your 4x4 binning addition for the IMX219. Will this allow for easier 120fps at 320x240? https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=250624
3. Have you actually done video capture into OpenCV? Looking at your forum post, it looks like you have a pipeline for still images.

**Comment by Hermann-SW** [comment]
Hi,
1) yes, but can be Pi or laptop CPU because it is done in post-processing
2) I don't know. I once had raspivid running 320x240@180fps with full FoV on v1 camera.
And tools/640x240 runs with 180fps even on v1 for raspiraw.
Since you are interested in full FoV you should use tools/640x480_s, that captures every other line of 640x480 full FoV, and generates 640x240 image. I did use "rasw2ogg2anim ... d" to double the lines in postprocessing and get 640x480 video/anim from it. For further processing no doubling is needed.
You can get your 320x240@180fps easily by taking every other column from captured 640x240 and have you 320x240 with full FoV for v1 camera.
3) OpenCV is too slow for me, for edge detection of only 320x240 images it did not allow to process more than 50 images per second (on Pi Zero)...
https://www.raspberrypi.org/forums/viewtopic.php?t=189661#p1250429

**Comment by bhjelstrom** [comment]
Thank you for your very prompt response. 

I suppose the best path forward for us is to enable 4x4 binning while using the v4l driver. Our pipeline runs well at 120fps, but we will need to have 320x240 at 120fps without debayering on the cpu to minimize pipeline time.

If I can somehow get in touch with you privately, I would love to show you what we're working on.
